services:

  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: bookstore-postgres
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: bookstore-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile
    container_name: bookstore-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstore
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/bookstore_logs
    depends_on:
      - postgres
      - mongodb

volumes:
  postgres_data:
  mongo_data:
