server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: book-service-books
          uri: http://localhost:8080
          predicates:
            - Path=/api/books/**

        - id: book-service-users
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**

        - id: book-service-orders
          uri: http://localhost:8080
          predicates:
            - Path=/api/orders/**

        - id: book-service-logs
          uri: http://localhost:8080
          predicates:
            - Path=/api/logs/**
